### ISSUE TITLE
JAR file cannot be opened

### ISSUE THREAD

**Issue by LimZhengJieBenjamin** [jaesimin/duke#9]
@jaesimin  All your iP peer reviewers reported that they could not get the JAR file to work. I tried it myself and it didn’t work on my computer either. This means we are unable to grade your iP.
Please release a new version that is cross-platform and confirmed to work with Java 11. When it is ready, post here to let me know ASAP (deadline: a week from today).

**Comment by jaesimin** [comment]
Okay, I've uploaded another release of the JAR file.
